language: node_js
node_js:
  - "12"
cache: npm
install:
  - cd backend
  - npm install
  - cd ..
  - npm install
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  skip-cleanup: true
  app:
    master: cise-seer
  on:
    all_branches: true
