language: node_js
services: mongodb
node_js:
  - "12"
cache: npm
install:
  - cd backend
  - npm install
  - cd ..
  - npm install
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: FX8wmaAfJyyrm6/5CugD+hAZrrbvMloBHrz9PiDk1OYZAoSAXp8ZJrB8BOy1iwVRxP9ZSAwqGJd/9aRvmiNUHJ39S5zcPfJ8wfcvc/PThP1dVBoMySGhiGRmWUv+13Du9w75VINUt5ES4Kh2WAdwhOCI91phamr6RGiz7hNQRwQgiMIxuDGR275XAGoj8NgYTvr6SiSo1AVF57oAdVP6/e19QHvzeS3t21Go1Hmdm8YCRf6RFNvzYKn22Oqn7oUep526b/6dlwYHz0LtONapsXuDffheB4RAUxZHi8kGRD4IkULUuyXCFUKjaI1SqghCrtyAA/oaNrT+y8D+yJJMhmfdod2+lQmm9x1vHMiSLW1WZRwLdOKC94SMFGmof7bS1zbXIEPybcyNrSIlPar0jcwTeeipxYyoowxhMbdxp3bIhk9X1aeHst/ccJVWvKwQTA+pOmbtHhI66wURZKtV1Q5VvzCV7NV70g3n1xXp7EDpbuwmacf/9ETaIEwlQnBHfxolnNKbamkiM+XONPmJbQ1nOGW+Of4zbKKtYlLAutsl0x6HtT1HqTSE4/H9FD17MVtY6kjG8tR8OW0RUndNhM8IkcDqidffH3Tt8sYhCXb2WfNTm+8d3Vm5RsugUR+6O5g+CjjvYKNvaoEzJ4XOVzfgWbmLkXZqYZK70TAHDjQ=
  skip_cleanup: true
  app:
    master: cise-seer
